@Is{!Environment.IvanTest}
public class CreatePromotionUS1864358{!Environment.IvanTest} {
    @Is{!Environment.IvanTest}
    static void testRun() {
        {!Environment.IvanTest}.start{!Environment.IvanTest}();
        try {
            CreatePromotionUS1864358.run();
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
        {!Environment.IvanTest}.stop{!Environment.IvanTest}();
        System.assert(true, 'Executed');
    }
}