@is{!Environment.IvanTest}
private class ExecConvert{!Environment.IvanTest}Lead1908669{!Environment.IvanTest} {
    @is{!Environment.IvanTest}
    static void testExecute() {
        {!Environment.IvanTest}.start{!Environment.IvanTest}();
        String result = ExecConvert{!Environment.IvanTest}Lead1908669.execute();
        {!Environment.IvanTest}.stop{!Environment.IvanTest}();
        System.assertNotEquals(null, result);
        System.assert(result.contains('status'));
    }
}